# GitHub metadata setup
owner: PengiCoder            # Replace with your GitHub username or organization
repo: pengi.au-status        # Replace with your Upptime repository name

# List of endpoints to monitor
sites:
  - name: Main Website
    url: https://pengi.au

  - name: Wiki
    url: https://wiki.pengi.au

  - name: TM API Health
    url: https://tm.pengi.au/health
    __dangerous__body_down_if_text_missing: '"ok": true'

# Status page setup
status-website:
  name: Pengi Status
  cname: status.pengi.au    # Optional: remove or update to your desired status domain
  theme: light

# Upptime configuration options
user-agent: UpptimeBot
